kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vwserver-claim
  labels:
    app: vwserver
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
