kind: PersistentVolume
apiVersion: v1
metadata:
  name: vwserver-volume
  labels:
    app: vwserver
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/data/

